export const TIPOS_USUARIO = {
  ADMIN: "ADMIN",
  JOGADOR: "JOGADOR",
};

export const STATUS_RESERVA = {
  ATIVA: "ATIVA",
  CANCELADA: "CANCELADA",
  CONCLUIDA: "CONCLUIDA",
};

export const STATUS_QUADRA = {
  DISPONIVEL: "DISPONIVEL",
  INDISPONIVEL: "INDISPONIVEL",
};
